#! /bin/sh -e

# Copyright (C) 2015 Tomoyuki Fujimori <moyu@dromozoa.com>
#
# This file is part of dromozoa-lambda.
#
# dromozoa-lambda is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dromozoa-lambda is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dromozoa-lambda.  If not, see <http://www.gnu.org/licenses/>.

output=$1
script=$2
case x$script in
  x) echo 'usage: dromozoa-lambda output script [args]'; exit 1;;
esac
shift 2

case x$TMPDIR in
  x) TMPDIR=/tmp;;
esac
tmp=`(umask 077 && mktemp -d "$TMPDIR/dromozoa-lambda-XXXXXXXX" 2>/dev/null || :)`
case x$tmp in
  x) tmp=$TMPDIR/dromozoa-lambda-$$-$RANDOM; (umask 077 && mkdir "$tmp");;
esac
trap "(cd / && rm -f -r '$tmp')" 0

dromozoa-amalgamate -o "$tmp/main.lua" "$script" "$@"
"$0-xml" "$@" >"$tmp/dromozoa-lambda.xml"
cp "$0.jar" "$tmp/output.jar"
(cd "$tmp" && zip -9q output.jar main.lua dromozoa-lambda.xml)
mv "$tmp/output.jar" "$output"
